FROM python:3.12-alpine

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# get curl for healthchecks
RUN apk add curl

WORKDIR /app
COPY . .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# running migrations
RUN python manage.py migrate
RUN python manage.py collectstatic --no-input

# define the port number the container should expose
# EXPOSE 5000

# gunicorn
# CMD ["gunicorn", "--config", "gunicorn-cfg.py", "project.wsgi"]