# Generated by Django 3.1.5 on 2021-01-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
