# Generated by Django 5.0.3 on 2024-03-15 15:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0006_alter_gun_id_alter_person_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='arma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='grocery_list.state'),
        ),
        migrations.DeleteModel(
            name='Gun',
        ),
    ]
