# Generated by Django 5.0.3 on 2024-03-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0008_rename_arma_person_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='nome',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
