# Generated by Django 5.0.3 on 2024-03-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0010_alter_person_sobrenome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['state']},
        ),
    ]
