# Generated by Django 5.0.3 on 2024-03-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0017_alter_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='on_cart',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
