# Generated by Django 3.1.5 on 2021-02-10 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_auto_20210130_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='arma',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulario.guns'),
        ),
    ]
