# Generated by Django 3.1.5 on 2021-02-10 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_auto_20210210_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='arma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='formulario.guns'),
        ),
    ]
