# Generated by Django 5.0.3 on 2024-03-15 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0007_state_alter_person_arma_delete_gun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='arma',
            new_name='state',
        ),
    ]
