# Generated by Django 5.0.3 on 2024-03-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0014_category_color_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
