# Generated by Django 5.0.3 on 2024-03-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0018_item_on_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
